# Generated by Django 3.2.9 on 2021-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eat',
            name='score',
            field=models.IntegerField(),
        ),
    ]
