# Generated by Django 3.2.9 on 2021-12-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_auto_20211210_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='review',
            field=models.CharField(max_length=512),
        ),
    ]
