# Generated by Django 3.2.9 on 2021-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_alter_eat_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='region',
            field=models.CharField(choices=[['울산', '울산'], ['서울', 'ㅅㅇ']], max_length=64),
        ),
    ]
